version: '3.8'

services:
  # Serviço do Banco de Dados
  postgres:
    image: postgres:15-alpine
    container_name: blog_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Aqui futuramente adicionaríamos o backend e frontend
  # Mas para desenvolver, rodaremos eles no terminal para ter "Hot Reload"

volumes:
  postgres_data: