version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: blog_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    # A imagem será puxada do seu ECR (vamos configurar a URL depois, por enquanto deixe assim)
    image: ${ECR_REPO_BACKEND}:latest
    container_name: blog_backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/blog_db?schema=public"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "3000:3000"
    restart: always

  frontend:
    # A imagem será puxada do seu ECR
    image: ${ECR_REPO_FRONTEND}:latest
    container_name: blog_frontend
    depends_on:
      - backend
    ports:
      - "80:3000" # Mapeia a porta 80 (padrão web) da EC2 para a 3000 do container
    restart: always

volumes:
  postgres_data: